name: neuroimagingenv
channels:
  - conda-forge
  - defaults
dependencies:
  - nibabel=3.0.1=py_0
  - pip=20.0.2=py_2
  - scipy=1.4.1=py36h9fa6033_0
  - statsmodels=0.11.0=py36h1de35cc_0
  - pip:
    - matplotlib
    - nilearn==0.6.2
    - numpy==1.18.1
    - scikit-learn==0.22.2.post1
    - sklearn==0.0
