name: neuroimagingenv
channels:
  - conda-forge
  - defaults
dependencies:
  - nibabel=3.0.1=py_0
  - pip
  - scipy
  - statsmodels
  - pip:
    - matplotlib
    - nilearn==0.6.2
    - numpy==1.18.1
    - scikit-learn==0.22.2.post1
    - sklearn==0.0
